spring.application.name=rti-portal
spring.datasource.url=jdbc:postgresql://localhost:5432/rti_portal
spring.datasource.username=postgres
spring.datasource.password=Pip432po0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true